#!/bin/bash
set -e

apt-get install -y openjdk-8-jdk maven

mvn -DskipTests=true compile && mvn -DskipTests=true clean install

cd openvidu-server

mvn clean compile package

cd target

cp openvidu-server-2.11.0.jar ../../openvidu-server-2.11.0.jar
