#!/bin/bash
set -e

apt-get install -y gnupg

echo "deb [arch=amd64] http://ubuntu.openvidu.io/6.11.0 bionic kms6" | tee /etc/apt/sources.list.d/kurento.list

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83

apt-get update

apt-get install -y kurento-media-server

sed -i "s/DAEMON_USER=\"kurento\"/DAEMON_USER=\"${USER}\"/g" /etc/default/kurento-media-server

apt-get install -y coturn redis-server openjdk-8-jre
