#!/bin/bash
set -e

update-java-alternatives -s java-1.8.0-openjdk-amd64

service redis-server start

service coturn start

service kurento-media-server start

java -jar -Dserver.ssl.key-store=/app/$KEYSTORE_NAME.jks -Dserver.ssl.key-store-password=$KEYSTORE_PASSWORD -Dserver.ssl.key-alias=$KEYSTORE_ALIAS -Dopenvidu.secret=$SECRET -Dopenvidu.publicurl=https://$PUBLIC_HOSTNAME:4443/ -Dopenvidu.recording=true -Dopenvidu.recording.path=/app/recordings -Dopenvidu.recording.autostop-timeout=30 openvidu-server-2.11.0.jar
