#!/bin/bash
set -e

service docker restart

service redis-server restart

service coturn restart

service kurento-media-server restart

java -jar -Dserver.ssl.key-store=/root/$KEYSTORE_NAME.jks -Dserver.ssl.key-store-password=$KEYSTORE_PASSWORD -Dserver.ssl.key-alias=$KEYSTORE_ALIAS -Dopenvidu.secret=$SECRET -Dopenvidu.publicurl=https://$PUBLIC_HOSTNAME:4443/ -Dopenvidu.recording=true -Dopenvidu.recording.path=/root/recordings -Dopenvidu.recording.autostop-timeout=30 -Dspring.profiles.active=docker /root/openvidu-server-2.11.0.jar
