name: Deployment
on:
  push:
    branches:
      - master
      - acceptance
      - 2.11.0
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker image and publish to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nerdsandcompany/openvidu
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
